### ISSUE TITLE
how do a give someone a life after they killed a green

### ISSUE THREAD

**Issue by sobly0** [LluisJM/Life-Series-Recreation#2]
how do i change someone to yellow after killing a green

**Comment by bananab77** [comment]
have you found a way ?

**Comment by bananab77** [comment]
nvm found it just do: /team join green_names <player>
you can change the team you want them to be by changing the color. ex: /team join red_names <player>

**Comment by LluisJM** [comment]
I am so sorry I didn't see this, I just switched phones and I hadn't installed GitHub. @bananab77 is completely right. As of the new version ([v2.0.0](https://github.com/LluisJM/Life-Series-Recreation/releases/tag/v2.0.0)), though, teams have been renamed (for example: `red_names` → `lsr.red`). I was planning to add this as a feature you can turn on and off with a setting. I'm so sorry again.
