### ISSUE TITLE
Unable to start pack

### ISSUE THREAD

**Issue by Tpguy2** [LluisJM/Life-Series-Recreation#3]
Please help. I have added the pack through modrinth then tried adding it manually when starting a singleplayer world. I do /trigger lsr.start_game and it comes up with "Unknown scoreboard objective 'lsr.start_game'. I then see if the data pack is in my world via /datapack list and it is! I am lost!

**Comment by LluisJM** [comment]
Hello! My best guess to what's happening is that you haven't confirmed your operator status, therefore you have no permission to start the game. When you first join, you are presented with a message that contains a button that says “Are you an operator?”. By clicking that, the datapack will check if you are indeed an operator ang give you permission to run many commands. I should really implement a better system than this, my apologies. To fix this problem, run `/function lsr:util/check_operator_status`, and then you should be able to open the Main Menu using `/trigger lsr.menu`.

I will be adding a better system, now that you have brought this to my attention. I hope it works for you, and thank you for downloading the datapack and taking the time to write this for me. :D

**Comment by LluisJM** [comment]
Currently, I can't find a way to check the player's operator status without using a clickable text. Because of this, I am not planning to fix this problem in the near future. However, I will try to fix it if I stumble into a way of doing it. Thank you for your feedback anyway! :D
