### ISSUE TITLE
Datapack isn't registered in world

### ISSUE THREAD

**Issue by Jeff-Pesos1** [LluisJM/Life-Series-Recreation#4]
So when I enter a world with operator permissions, it doesn't pop up with the chat message, and if I do any command, nothing works, it also isn't viewed as a datapack in my world, it's just not registered in. Is there a certain version it has to be in or am I doing something wrong. I am using the modrinth download by the way.

**Comment by Jeff-Pesos1** [comment]
Also is this compatible with the essentials modpack?
If not can you please make it compatible with it because its the only way I can do it with my friends without risking my IP address or paying money.

**Comment by LluisJM** [comment]
Weird. I would like you to go to the world folder and check the datapack is in there and that, just inside it, there's a folder called `data`, a file named `pack.mcmeta` and a PNG called `pack.png`. I'm telling you this because sometimes zips can have different levels and Minecraft can't read them. (By the way, which Minecraft version and version of the datapack are you using?). If that's the case, could you please send me the world files, so I can try to figure out what's wrong?

About Essential, the datapack is fully compatible! In fact, I have done all my playtesting with my friends using the mod. :D

**Comment by Jeff-Pesos1** [comment]
This is weird... I go into my file explorer and I cant find the file, is there another way you want me to view it, or possibly it has a different name? I am downloading this and playing it off of 1.20.2. Should I do a different version?

**Comment by Jeff-Pesos1** [comment]
When I put the folder in the comment, it does a link. How do I send you the file?

**Comment by LluisJM** [comment]
Hm... Maybe compress it and send the .ZIP? Also, use the button that reads "Attach Files", or something along those lines.

**Comment by LluisJM** [comment]
If that doesn't work, just DM me the file through Discord (User: lluis_jm)

**Comment by Jeff-Pesos1** [comment]
yeah got no discord so cant you go into modrinth and view the file and tell me if it's just a glitch with my thing? Because if it does work for you then I probably have to update my modrinth. I am also using version 1.20.2

**Comment by LluisJM** [comment]
I am on a trip right now, so I don't have my computer, but I do test every version before publishing, and I am very sure the data pack version worked, although I didn't test it on 1.20.2, hence probably the problem. I'll be able to work on it on Friday. In the mean time, could you try running the data pack on newer versions, please? Just to check if that still works.

**Comment by Jeff-Pesos1** [comment]
yeah i gotchu

**Comment by LluisJM** [comment]
Okay, so, I'm back from my trip and I just tried installing the datapack from the Modrinth app. Apparently, Modrinth does not automatically add data packs to worlds, but rather adds them to a folder called `datapacks` in the profile folder and you have to add them manually as indicated in [this tutorial](https://www.youtube.com/watch?v=sdPObv_UjSk) that I found. I don't know if that's your problem. Could you try it and tell me the results, please?

**Comment by Jeff-Pesos1** [comment]
it seemed to have worked, and sorry I had a lot of things I needed to do recently, but thank you I can now recreate 3rd life with my friends!

**Comment by LluisJM** [comment]
I'm really happy it worked for you! I hope you have a good time with your friends!
