### ISSUE TITLE
Please mention the set lives command in the datapack description

### ISSUE THREAD

**Issue by Jabbe04** [LluisJM/Life-Series-Recreation#5]
I tried out this datapack and noticed, that you cannot set the lifes of the players with any of the command mentioned in the datapack description. If you are doing a life series project and you have to refund a life because of an illegal kill or you want to give players lifes for kills you have to look through the datapack files to find the function that sets player lives. I found the command to set lives "execute run team join lsr.green @s"(or lsr.yellow and lsr.red for yellow and red) to set player lives after like half an hour of searching. If the command is already there please put it next to the other commands in the datapack description, so that other players don't get the same problem and might not be able to solve it like me.

**Comment by LluisJM** [comment]
I hadn't thought about that. You are absolutely right. Right now, I can't code nor test anything because I'm on a trip, but I'll work on it when I can (probably on Friday afternoon). I'll probably add a command that adds a life to the executer. Thank you for bringing this out. :D

**Comment by LluisJM** [comment]
I just fixed the issue by adding a new function: `lsr:util/add_life_to_player`, which can be used to manually add a life to a specific player. Thank you again for your feedback. :D

**Comment by Jabbe04** [comment]
That is nice to hear, that you added the life-add command. That will surely make the datapack better.Von meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Lluís ***@***.***> Datum: 20.12.24  17:24  (GMT+01:00) An: LluisJM/Life-Series-Recreation ***@***.***> Cc: Jabbe04 ***@***.***>, Author ***@***.***> Betreff: Re: [LluisJM/Life-Series-Recreation] Please mention the set lives command in the datapack description (Issue #5) 
I just fixed the issue by adding a new function: lsr:util/add_life_to_player, which can be used to manually add a life to a specific player. Thank you again for your feedback. :D
